version: '3.8'

services:
  bot:
    build: .
    container_name: lati_gemini_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DB_FILE=/app/data/chat_history.db
